# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-01-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_matchreport_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='matchReport',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='news_cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.News'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatchReport',
        ),
    ]
