# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-01-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='matchreport',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
