# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-01-13 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190113_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
