# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-02-11 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190113_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='report_images/'),
        ),
    ]
